config/routes.rb
Rails.application.routes.draw do
  resources :software
  resources :projects
  resources :skills
  resources :posts
  resources :social_handles, only: [:index]
  resources :contact, only: [:index, :new, :create] 
  #post '/send_message', to: 'contact#send_message'
  devise_for :users
  get 'profiles/index'
  root to: "profiles#index"
  get '/about', to: 'profiles#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def index
    @last_posts = Post.last(6)
    @projects = Project.all
  end

  def about
  @skills = Skill.all
  @projects = Project.all.order(:created_at)
  end
  
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_about_section.html.erb
<div class="container-fluid text-md-start mt-5">
  <div class="row">
    <div class="col-md-12 col-12">
      <div class="d-flex row about_row">
        <div class="col-md-6 col-12 text-center" data-aos="fade-up">
          <img  class="img-thumbnail thumbnail_img" src="<%= asset_path('thumbnail.jpg') %>" alt="create" />
        </div>
        <div class="col-md-6 col-sm-12 mt-2 about_me_data" >
         <div data-aos="fade-down">
            <h6 class="bio_title">BIOGRAPHY</h6>
            <h1 class="about_me_title">ABOUT ME</h1>
            <p>Hi! I am<span class="bio_title"> Vishwani Patlan</span>. Being a developer for 1.6+ years, I have been enjoying this journey in which I had learned, participated, and contributed to the various projects that I have been part of. I believe that actual coding is less than 50% of a developer's work. Right from understanding and analyzing the project requirements, I work on various other things to ensure the success of the project. I believe in solving the issue before I start coding. The design, architecture, plan is vital in creating a great stable, and callable product.</p>
            <%= link_to about_path, method: :get, class: 'btn know_more_button' do %>
              <span class="btn-text">Know more about me  <i class="fas fa-long-arrow-alt-right"></i></span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/_blog_section.html.erb
<div class="container-fluid">
  <h1 class="text-center" style="font-weight: bolder; color: #521634b5;">LATEST BLOGS</h1>
  <div class="row" style="display: flex; flex-direction: row;justify-content: space-evenly;">
    <% @last_posts.each do |post| %>
      <%= link_to(post, class: "col-md-4 col-12 blog_card") do %> 
        <div>
          <div class="card bg-dark text-white card_blog">
            <%= image_tag(post.image.present? ? post.image : " ", class: 'card-img', style: 'width: 100%') %>
            <div class="card-img-overlay">
              <h5 class="card-title"><%= post.title %></h5>
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <p class="card-text">Last updated 3 mins ago</p>
            </div>
        </div>
    </div>
    <% end %>
   <% end %> 
  </div>
</div>

app/views/profiles/_education.html.erb
<div class="container">
    <div class="mb-5" data-aos="fade">
      <h1 class="text-center" style="font-weight: bolder;">My Qualifications and Work Experince</h1>
    </div>
    <div class="row">
      <div class="col-md-6 col-12">
       <div class="card text-center" data-aos="flip-up">
          <div class="card-header">
            GRADUATION
          </div>
          <div class="card-body">
            <h5 class="card-title">Bachelor of Technology</h5>
            <p class="card-text">Branch Electonics And Communication</p>
            <h6><strong>Result:</strong> 7.5 CGPA<p>(In scale of 10)</p></h6>
            <p><strong>Division Awarded: </strong>I-DIV HONS</p>
          </div>
          <div class="card-footer text-muted">
            Session: 2016-2020
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-6"></div>
      <div class="col-md-6 col-12">
        <div class="card text-center" data-aos="flip-down">
          <div class="card-header">
            INTERMEDIATE
          </div>
          <div class="card-body">
            <h5 class="card-title">Science</h5>
            <p class="card-text">Physics Chemistry Maths (PCM)</p>
            <h6><strong>Result:</strong> 7.2<p>(In scale of 10)</p></h6>
            <p><strong>Division Awarded: </strong>I-DIV</p>
          </div>
          <div class="card-footer text-muted">
            Session: 2015-2016
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 col-12">
        <div class="card text-center" data-aos="flip-up">
          <div class="card-header">
            HIGH SCHOOL
          </div>
          <div class="card-body">
            <h5 class="card-title">Science</h5>
            <p class="card-text">Science Engish Hindi Math Social-Science</p>
            <h6><strong>Result:</strong> 9.2 CGPA<p>(In scale of 10)</p></h6>
            <p><strong>Division Awarded: </strong>I-DIV</p>
          </div>
          <div class="card-footer text-muted">
            Session: 2013-2014
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6"></div>
      <div class="col-md-6 col-12">
        <div class="card text-center" data-aos="flip-up">
          <div class="card-header">
            Software Developer
          </div>
          <div class="card-body">
            <h5 class="card-title">Ruby on Rails Developer</h5>
            <p class="card-text">GRK info services pvt ltd.</p>
            <h6><strong>Technology Worked on:</strong><p>ROR, Javascript , HTML, CSS, jQuery, etc.</p></h6>
            <p><strong>Award: </strong>Best Trainer</p>
          </div>
          <div class="card-footer text-muted">
            Session: 2020-Present
          </div>
        </div>
      </div>
    </div>
</div>

app/views/profiles/_exeperince_education.html.erb
<button class="bg-white text-dark fw-bold p-3 fs-3 rounded-pill text-decoration-none" style="border: none;" type="button"  data-bs-toggle="modal" data-bs-target="#staticBackdrop">
  Exeperince & Education
</button>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Exeperince & Education</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
    <div class="work-education row">
    <div class="col-sm-12 col-md-6 col-lg-6">
      <ul class="work-ul">
        <span><div class="icon">
        <i class="fa fa-briefcase"></i></div><li class="work-experience-education">
          <span><p>2020-Present</p></span>
          <h4>Sofwatre Developer - <small>GRK Info Services Pvt Ltd</small></h4>
          <p>
            <ul>
              <li>Work on MVC Model View Controller architecture and frameworks.</li>
              <li>Re-write web pages in Ruby using Rails framework.</li>
              <li>Implement Ajax for dynamic updating of the part of a page, avoiding full page refresh.</li>
              <li>Develop validation methods in models to validate data input by users.</li>
              <li>Involved in gathering user requirements, system analysis, design, development, testing and implementation.</li>
              <li>Use of Git and GitHub repositories.</li>
              <li>Strong knowledge using the CRUD , create, read, update and delete methodology.</li>
            </ul>
          </p>
        </li></span>
      </ul>
    </div>
    <div class="col-sm-12 col-md-6 col-lg-6">
      <ul class="education-ul">
        <span><div class="icon"><i class="fa fa-briefcase"></i></div><li class="work-experience-education">
          <span><p>2020</p></span>
          <h4>ENGINEERING DEGREE - Uttar Pradesh Technical University</h4>
          <p>Complete engineering in Electronics and Communication</p>
        </li></span>
        <span><div class="icon"><i class="fa fa-briefcase"></i></div><li class="work-experience-education">
          <span><p>2016</p></span>
          <h4>INTERMEDIATE - Lal Dayal Public School</h4>
          <p>Complete intermediate with PCM</p>
        </li></span>
        <span><div class="icon"><i class="fa fa-briefcase"></i></div><li class="work-experience-education">
          <span><p>2014</p></span>
          <h4>HIGH SCHOOL - Shri Ram Public School</h4>
          <p>Complete my schooling with subjects like Maths, Science, English, Hindi, Social Sciene</p>
        </li></span>
      </ul>
    </div>
  </div>
      </div>

    </div>
  </div>
</div>

app/views/profiles/_project_details.html.erb
<div class="wrapper projects">
  <h1 class="text-center mb-4">Projects Information</h1>
  <div class="wrapper project-details">
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <% @projects.each_with_index do |project, idx| %>
        <% class_name =  idx==0 ? 'active' : '' %>
        <div class="carousel-item <%= class_name%>">
          <div class="row">
            <div class="col-ld-6 col-md-5 col-sm-12 pt-5 project-img">
              <% if project.image_url.present? %>
                <img src="<%= asset_path(project.image_url) %>" alt="project-image" class="mt-2 form-image">
              <% else %>
                <img src="<%= asset_path('santaUI.png') %>">
              <% end %>
            </div>
            <div class="col-lg-6 col-md-7 col-sm-12 pt-5 project-data">
              <h1 class="text-center"><a href="<%= project.url %>" target="_blank"><%= project.name %></a></h1>
              <div class="project-description">
                <p><%= project.description %></p>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
</div>


<div class="wrapper services">
  <h1 class="text-center">Services</h1>
  <div class="wrapper services-details">
    <div class="row pt-4 services-row">
      <div class="col-lg-4 col-md-4 mt-5 col-sm-12" data-aos="fade-down" data-aos-delay="60">
        <img src="<%= asset_path('developer.png')%>" alt="">
        <h3>Development</h3>
      </div>
      <div class="col-lg-4 col-md-4 mt-5 col-sm-12" data-aos="fade-up" data-aos-delay="60">
        <img src="<%= asset_path('Freelancer.png')%>" alt="">
        <h3>Freelancing</h3>
      </div>
      <div class="col-lg-4 col-md-4 mt-5 col-sm-12" data-aos="fade-down" data-aos-delay="60">
        <img src="<%= asset_path('consultant.png')%>" alt="">
        <h3>Consultant</h3>
      </div>
    </div>
  </div>
</div>

app/views/profiles/_skills_section.html.erb
<div class="container-fluid text-md-start mt-5">
  <div class="row">
    <div class="col-md-12 col-12">
      <div class="d-flex row skills_row">
        <div class="col-md-6 col-12">
          <div class="container p-3 mt-3 mb-2 skill_block" data-aos="flip-left" style="background: #b4c1d4;">
            <h2 class="text-center mt-4" style="font-weight: bolder;">SKILLS</h3>
            <div class="row p-3">
              <div class="col-12 mb-2">
                <div class="mb-2">Ruby on rails</div>
                <div class="skill skill1" data-aos="fade-down">80%</div>
              </div>
               <div class="col-12 mb-2">
                <div class="mb-2">HTML</div>
                <div class="skill skill2" data-aos="fade-down">80%</div>
              </div>
               <div class="col-12 mb-2">
                <div class="mb-2">JavaScript</div>
                <div class="skill skill3" data-aos="fade-down">75%</div>
              </div>
               <div class="col-12 mb-2">
                <div class="mb-2">JQuery</div>
                <div class="skill skill4" data-aos="fade-down">70%</div>
              </div>
               <div class="col-12 mb-2">
                <div class="mb-2">Bootstrap</div>
                <div class="skill skill6" data-aos="fade-down">60%</div>
              </div>
              <div class="col-12 mb-2">
                <div class="mb-2">CSS</div>
                <div class="skill skill5" data-aos="fade-down">50%</div>
              </div>
              <div class="col-12 mb-2">
                <div class="mb-2">Git</div>
                <div class="skill skill6" data-aos="fade-down">60%</div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-12">
           <div class="container p-3 mt-3 mb-3 p-3 tool_block" data-aos="flip-right" style="background: #b4c1d4;">
           <h2 class="text-center" style="font-weight:bolder;">Tools And Technologies Used</h3>
            <div class="row p-3 mb-4">
              <div class="col-md-6 col-6 item" data-aos="fade-down">
                <h5 class="text-center">Sublime Text 3</h5>
                <img class="tools_size sublime" src="<%= asset_path('sublime.png') %>">
              </div>
              <div class="col-6 col-md-6" data-aos="fade-down">
                <h5 class="text-center">VS Code</h5>
                <img class="tools_size vscode" src="<%= asset_path('vscode.png') %>">
              </div>
            </div>
             <div class="row p-3 mt-2">
              <div class="col-md-6 col-6" data-aos="fade-up">
                <h5 class="text-center">Github</h5>
                <img class="tools_size github " src="<%= asset_path('github.png') %>">
              </div>
              <div class="col-6 col-md-6" data-aos="fade-up">
                <h5 class="text-center">JIRA</h5>
                <img class="tools_size jira " src="<%= asset_path('jira.png') %>">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/about.html.erb
<div class="main-page">
  <div><%= render 'layouts/navbar' %></div>
  <div class="container-fluid my-3 shadow-lg bg-light ">
    <div class="row text-center px-3 align-items-center py-3">
      <div class="col-2 ">
        <%= link_to ('<i class="fa fa-arrow-left"></i>').html_safe, root_path, class:"text-dark fs-1 align-items-start "%>
      </div>
      <div class="col-8">
        <h2 class="text-dark">ABOUT ME</h2>
      </div>
      <div class="col-2">
        <img src="<%=asset_path('about_logo.png')%>" style= "width: 60px; height: 60px;" >
      </div>
    </div>
  </div>
  <hr class="featurette-divider mx-5 text-light">
    <div class="container bg-light my-5 rounded-3 border shadow">
      <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center ">
        <div class="col-lg-7 p-3 p-lg-5 pt-lg-3">
          <h1 class="text-dark fw-bold lh-1">Hello, I'M Vishwani Patlan Full Stack Developer From Delhi, India!</h1>
          <p class="lead fs-3 fst-italic my-5">
              Experienced software developer with a passion for developing innovative programs that
              expedite the  efficiency and effectiveness of organizational success. Well-versed in
              technology and writing code to create applications that are reliable and user-friendly.
              Skilled leader who has the proven ability to motivate, educate, and manage a team of
              professionals to build applications with quality. Confident communicator, strategic thinker,
              and innovative creator to develop software that is customized to meet a company’s organizational
              needs, and further their success.
            </p>
        </div>
        <div class="col-lg-4 offset-lg-1 p-0 overflow-hidden ">
            <img class="bd-placeholder-img"style= "width: 600px; height: 600px;" src="<%= asset_path('ProfilePic.png') %>" alt="vishwani-image" >
        </div>
      </div>
    </div>
  <div class="container bg-light rounded-3 border shadow">
    <h2 class="text-center mt-3">Exeperince & Education</h2>
    <hr class="featurette-divider mx-5 text-dark">
    <div class="work-education row my-5">

      <div class="col-sm-12 col-md-6 col-lg-6">
        <ul class="work-ul">
          <span><div class="icon">
          <i class="fa fa-briefcase"></i></div><li class="work-experience-education">
            <span><p>2020-Present</p></span>
            <h4>Sofwatre Developer - <small>GRK Info Services Pvt Ltd</small></h4>
            <p>
              <ul>
                <li>Work on MVC Model View Controller architecture and frameworks.</li>
                <li>Re-write web pages in Ruby using Rails framework.</li>
                <li>Implement Ajax for dynamic updating of the part of a page, avoiding full page refresh.</li>
                <li>Develop validation methods in models to validate data input by users.</li>
                <li>Involved in gathering user requirements, system analysis, design, development, testing and implementation.</li>
                <li>Use of Git and GitHub repositories.</li>
                <li>Strong knowledge using the CRUD , create, read, update and delete methodology.</li>
              </ul>
            </p>
          </li></span>
        </ul>
      </div>

    <div class="col-sm-12 col-md-6 col-lg-6">
      <ul class="education-ul">
        <span><div class="icon"><i class="fa fa-briefcase"></i></div><li class="work-experience-education">
          <span><p>2020</p></span>
          <h4>ENGINEERING DEGREE - Uttar Pradesh Technical University</h4>
          <p>Complete engineering in Electronics and Communication</p>
        </li></span>
        <span><div class="icon"><i class="fa fa-briefcase"></i></div><li class="work-experience-education">
          <span><p>2016</p></span>
          <h4>INTERMEDIATE - Lal Dayal Public School</h4>
          <p>Complete intermediate with PCM</p>
        </li></span>
        <span><div class="icon"><i class="fa fa-briefcase"></i></div><li class="work-experience-education">
          <span><p>2014</p></span>
          <h4>HIGH SCHOOL - Shri Ram Public School</h4>
          <p>Complete my schooling with subjects like Maths, Science, English, Hindi, Social Sciene</p>
        </li></span>
      </ul>
    </div>
  </div>
  </div>


  <hr class="featurette-divider mx-5 text-light">

  <div class="container px-4 py-5" id="custom-cards">
    <h2 class="pb-2 border-bottom text-white">About My knowledge</h2>

    <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
      <div class="col">
        <a href="/software" class="text-decoration-none">
          <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" >
            <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
              <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold text-dark">Software Info</h3>
            </div>
          </div>
        </a>  
      
      </div>

      <div class="col">
        <a href="/skills" class="text-decoration-none">
          <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" >
            <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
              <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold text-dark">Skills & Knowledge</h3>
            </div>
          </div>
        </a>
      
      </div>

    </div>
  </div>
</div>

app/views/profiles/contact.html.erb
<div class="main-about-page">
  <div><%= render 'layouts/navbar' %></div>

  <div class="container tools-technology ">
    <div class="tools-tech-header">
      <h2 class="text-center">GET IN TOUCH!</h2>
    </div>
    <div id="success-mail-alert" class="alert alert-success container text-center" style="display: none;" role="alert">
      Your Message Send Successfully!
    </div>
    <div id="fail-mail-alert" class="alert alert-danger container text-center" style="display: none;" role="alert">
      Some Error Occured!
    </div>
    <div class="row">
      <div class="col-md-4 col-lg-4 contact-left">
        <ul>
          <li>
            <h4>DON'T BE SHY !</h4>
            <p>
              Feel free to get in touch with me.I am always open
              to discussing new projects, creative ideas or
              opportunities to be part of your visions.
            </p>
          </li>
          <li>
            <span><div><i class="fas fa-home"></i></div><p>ADDRESS</p></span>
            <p>Sagarpur,New Delhi,110046,India</p>
          </li>
          <li>
            <span><div><i class="fas fa-envelope-open"></i></div><p>MAIL ME</p></span>
            <p><a href="mailto:vishwani123patlan@gmail.com">vishwani123patlan@gmail.com</a></p>
          </li>
          <li>
            <span><div><i class="fas fa-phone-square-alt"></i></div><p>CALL ME</p></span>
            <p>+91-8755339910</p>
          </li>
          <li>
            <h6>FOLLOW ME</h6>
            <div class="social-media">
              <a href="#"><i class="fab fa-linkedin"></i></a>
              <a href="#"><i class="fab fa-facebook"></i></a>
              <a href="#"><i class="fab fa-instagram"></i></a>
              <a href="#"><i class="fab fa-github"></i></a>
            </div>
          </li>
        </ul>
      </div>

      <div id="contact-form-section" class="col-md-8 col-lg-8 contact-form">
        <%= render 'contact_form'%>
      </div>
    </div>
  </div>
</div>  

app/views/profiles/index.html.erb
<div class="main-page">
  <div><%= render 'layouts/navbar' %></div>
  <div class="container-fluid my-5 shadow-lg" style="background-image: url(<%= asset_path('bck2.jpg')%>);">
    <div class="row text-center p-4 pb-0 pe-lg-0  align-items-center border shadow-lg">
      <div class="col">
        <img class="mt-3" src="<%=asset_path('about-section.png')%>" style= "width: 300px; height: 300px; border-radius: 50%;">
        <h2 class="mt-3">Hi!!.. I'M VISHWANI RAJPUT</h2>
        <p class="fs-5 fw-bold">( A Full Stack Developer, From Delhi-India! )</p>
      </div>
    </div>
  </div>

  <div class="container-fluid my-5">
  <div class="row text-center p-4 pb-0 pe-lg-0 py-lg-3 align-items-center ">
    <div class="col">
      <hr class="featurette-divider mx-5 text-light">
        <h1 class="text-white">Being A Full Stack Developer</h1>
        <p class="fs-5">( It’s amazing how much ground is constantly being broken in this field, So constantly learning new concepts and technologies )</p>
       <hr class="featurette-divider mx-5 text-light">
          <div class="container my-5 rounded-3 border shadow-lg" style="background-color: white;">
            <div class="row text-center  pb-0 pe-lg-0 py-lg-3 align-items-center">
                <div class="container marketing my-3">
                  <h1 class="text-dark">Explore The Portfolio</h1>
                  <hr class="featurette-divider mx-5 text-dark">
                  <div class="row text-center">
                    <div class="col-lg-4 my-5">
                        <img src="<%= asset_path('about_logo.png')%>" class="bd-placeholder-img", style= "width: 180px; height: 180px;" >
                      <h2 class="my-3 text-dark">About Me</h2>
                      <%= link_to "Read More »", about_path, class: "btn btn-outline-dark  fs-5 d-grid gap-2 d-md-block" %>
                    </div>
                    <div class="col-lg-4 my-5">
                        <img src="<%= asset_path('skill_logo2.png')%>" class="bd-placeholder-img ", style= "width: 180px; height: 180px;" >
                      <h2 class="my-3 text-dark">My Skills</h2>
                      <%= link_to "View »", skills_path, class: "btn btn-outline-dark  fs-5 d-grid gap-2 d-md-block" %>
                    </div>
                    <div class="col-lg-4 my-5">
                        <img src="<%= asset_path('project_logo.png')%>" class="bd-placeholder-img", style= "width: 180px; height: 180px;" >
                      <h2 class="my-3 text-dark">Projects</h2>
                      <%= link_to "View »", projects_path, class: "btn btn-outline-dark  fs-5 d-grid gap-2 d-md-block" %>
                    </div><!-- /.col-lg-4 --> 
                  </div>
                </div>
            </div>
          </div>
      <hr class="featurette-divider mx-5 text-light my-5">     
    </div>
  </div>
</div>
</div>