config/routes.rb
Rails.application.routes.draw do
  resources :software
  resources :projects
  resources :skills
  resources :posts
  resources :social_handles, only: [:index]
  resources :contact, only: [:index, :new, :create] 
  #post '/send_message', to: 'contact#send_message'
  devise_for :users
  get 'profiles/index'
  root to: "profiles#index"
  get '/about', to: 'profiles#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/software.rb
class Software < ApplicationRecord
	validates :name, :about, presence: true
	has_one_attached :image
end

app/controllers/software_controller.rb
class SoftwareController < ApplicationController
    before_action :set_software, only: %i[ show edit update]

  def index
    @softwares = Software.all
  end

  def new
    @software = Software.new
  end

  def show
  end

  def create
    @software = Software.new(software_params)
      respond_to do |format|
        if @software.save 
          format.html { redirect_to @software, notice: "software was successfully created." }
          format.json { render :show, status: :created, location: @software }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @software.errors, status: :unprocessable_entity }
        end
      end  
  end

  def edit
  end

  def update
    respond_to do |format|
        if @software.update(software_params) 
          format.html { redirect_to @software, notice: "software was successfully updated." }
          format.json { render :show, status: :created, location: @software }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @software.errors, status: :unprocessable_entity }
        end
      end  
  end


  private

    def set_software 
      @software = Software.find(params[:id])
    end

    def software_params
      params.require(:software).permit(:name, :about, :image)
    end
end

app/helpers/software_helper.rb
module SoftwareHelper
end

app/views/software/_form.html.erb
<%= form_with(model: @software, url: software_index_path, method: :post) do |form|%>
  <% if @software.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@software.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
        <% @software.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <span onchange="loadFile(event)"><%= form.file_field :image %></span>
    <p class="logo-image"><img id="output" width="200px;"/></p>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>







<script>
var loadFile = function(event) {
  var image = document.getElementById('output');
  image.src = URL.createObjectURL(event.target.files[0]);
};
</script>

app/views/software/edit.html.erb
<h1>Software#edit</h1>
<%= render 'form', software: @software %>

<%= link_to 'Back', software_index_path %>

app/views/software/index.html.erb
<div class="main-page">
  <div><%= render 'layouts/navbar' %></div>
  <div class="container-fluid my-3 shadow-lg bg-light ">
    <div class="row text-center px-3 align-items-center py-3">
      <div class="col-2 ">
        <%= link_to ('<i class="fa fa-arrow-left"></i>').html_safe, about_path, class:"text-dark fs-1 align-items-start "%>
      </div>
      <div class="col-8">
        <h2 class="text-dark">SOFTWARE INFO</h2>
      </div>
      <div class="col-2">
        <img src="<%=asset_path('software.png')%>" style= "width: 60px; height: 60px;" >
      </div>
    </div>
  </div>
  <hr class="featurette-divider mx-5 text-light">
      	<div class="container marketing my-5">
        	<div class="row text-center">
        		<% @softwares.each do |software|%>
	          		<div class="col-lg-4 ">
	          			<% if software.image.attached? %>
	                 			<%= image_tag software.image,class:"bd-placeholder-img rounded-circle", style: "width: 180px; height: 180px;" %>
	                		<%end%>
	            		<h2><%= software.name %></h2>
	            		<p><%= truncate(strip_tags(software.about),length: 120) %></p>
	            		<%= link_to "View »", software_path(software.id), class: "btn btn-outline-light" %>
	          		</div><!-- /.col-lg-4 -->
          		<%end%>
      	</div>
      	</div>
      <hr class="featurette-divider mx-5 text-light">
</div>  

app/views/software/new.html.erb
<h1>Software#new</h1>

<%= render 'form', software: @software %>

<%= link_to 'Back', software_index_path %>

app/views/software/show.html.erb
<div class="main-about-page">
   <%= render 'layouts/navbar' %>
<div class="container-fluid my-3 shadow-lg bg-light ">
    <div class="row text-center px-3 align-items-center py-3">
      <div class="col-12 ">
        <%= link_to ('<i class="fa fa-arrow-left"></i>').html_safe, software_index_path, class:"mx-5 text-dark fs-1 align-items-start "%>
      </div>
    </div>
  </div>

<hr class="featurette-divider mx-5 text-light">
    <div class="container bg-light my-5 rounded-3 border shadow">
      <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center ">
        <div class="col-lg-7 p-3 p-lg-5 pt-lg-3">
          <h1 class="text-dark fw-bold lh-1"><%= @software.name %></h1>
          <p class="lead fs-3 fst-italic my-5"><%= @software.about %></p>
        </div>
        <div class="col-lg-4 offset-lg-1 p-0 overflow-hidden ">
            <% if @software.image.attached? %>
                    <%= image_tag @software.image, class:"bd-placeholder-img", style: "width: 500px; height: 500px;" %>
                <%end%>
        </div>
      </div>
</div>
<hr class="featurette-divider mx-5 text-light">