config/routes.rb
Rails.application.routes.draw do
  resources :software
  resources :projects
  resources :skills
  resources :posts
  resources :social_handles, only: [:index]
  resources :contact, only: [:index, :new, :create] 
  #post '/send_message', to: 'contact#send_message'
  devise_for :users
  get 'profiles/index'
  root to: "profiles#index"
  get '/about', to: 'profiles#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  has_rich_text :description
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :likes, :dislikes, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.rich_text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :likes %>
    <%= form.number_field :likes %>
  </div>

  <div class="field">
    <%= form.label :dislikes %>
    <%= form.number_field :dislikes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="main-page">
  <div><%= render 'layouts/navbar' %></div>
  <div class="container-fluid my-3 shadow-lg bg-light ">
    <div class="row text-center px-3 align-items-center py-3">
      <div class="col-2 ">
        <%= link_to ('<i class="fa fa-arrow-left"></i>').html_safe, root_path, class:"text-dark fs-1 align-items-start "%>
      </div>
      <div class="col-8">
        <h2 class="text-dark">Blogs</h2>
      </div>
      <div class="col-2">
        <img src="<%=asset_path('blog.png')%>" style= "width: 60px; height: 60px;" >
      </div>
    </div>
  </div>
    <hr class="featurette-divider mx-5 text-light">
      <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <% @posts.each do |post|%>
          <div class="col">
            <div class="card shadow-sm">
              <% if post.image.attached? %>
                 <%= image_tag post.image, class:"bd-placeholder-img", style: "width: 100%; height: 225px;" %>
                <%end%><text class="text-center fs-3 fw-bold"><%= post.title %></text>
              <div class="card-body">
                <p class="card-text fst-italic"><%= truncate(strip_tags(post.description.to_plain_text),length: 120)%></p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                     <%= link_to "View", post_path(post.id), class: "btn btn-outline-dark" %>
                  </div>
                  <small class="text-muted">9 mins</small>
                </div>
              </div>
            </div>
          </div>
        <%end%>
      </div>
    </div>
  <hr class="featurette-divider mx-5 text-light"> 
  </div> 
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="main-page">
  <div><%= render 'layouts/navbar' %></div>
  <div class="container-fluid my-3 shadow-lg bg-light ">
    <div class="row text-center px-3 align-items-center py-3">
      <div class="col-12 ">
        <%= link_to ('<i class="fa fa-arrow-left"></i>').html_safe, posts_path, class:"mx-5 text-dark fs-1 align-items-start "%>
      </div>
    </div>
  </div>
  <hr class="featurette-divider mx-5 text-light">
    <div class="container bg-light my-5 rounded-3 border shadow">
      <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center ">
        <div class="col-lg-7 p-3 p-lg-5 pt-lg-3">
          <h1 class="text-dark fw-bold lh-1"><%= @post.title %></h1>
          <p class="lead fs-3 fst-italic my-5"><%= @post.description %></p>
        </div>
        <div class="col-lg-4 offset-lg-1 p-0 overflow-hidden ">
            <% if @post.image.attached? %>
                    <%= image_tag @post.image, class:"bd-placeholder-img", style: "width: 500px; height: 500px;" %>
                <%end%>
        </div>
      </div>
</div>
<hr class="featurette-divider mx-5 text-light">     